<?php
$store = Mage::app()->getStore();
$code  = $store->getCode();
    $_enable = Mage::getStoreConfig('porto_settings/contacts/enable', $code);
    if($_enable){
        $_address = Mage::getStoreConfig('porto_settings/contacts/address', $code);
        $_zoom = Mage::getStoreConfig('porto_settings/contacts/zoom', $code);
        $_center_lat = Mage::getStoreConfig('porto_settings/contacts/latitude', $code);
        $_center_lng = Mage::getStoreConfig('porto_settings/contacts/longitude', $code);
?>
<!-- <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.17"></script>
<script type="text/javascript">
    function initialize() {
        var pos = new google.maps.LatLng(<?php //echo $_center_lat; ?>, <?php //echo $_center_lng; ?>);
        var mapOptions = {
            center: pos,
            panControl: true,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            overviewMapControl: true,
            zoom: <?php// echo $_zoom; ?>
        };
        var map = new google.maps.Map(document.getElementById("store_map"), mapOptions);
        var marker = new google.maps.Marker({
            position: pos,
            map: map,
            title: '<?php //echo $_address; ?>'
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script> -->

<?php
    if(Mage::getStoreConfig("porto_settings/header/type",$code) == "10"){
?>
<div class="page-header">&nbsp;</div>
<?php
    }
?>
<div id="store_map" style="min-height: 300px; width: 100%;">
    
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3312.946015119675!2d151.05898235046797!3d-33.8652821262121!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b12bb44f2fd18bd%3A0xe35269bb280852f8!2s13%2F159+Arthur+St%2C+Homebush+West+NSW+2140%2C+Australia!5e0!3m2!1sen!2sin!4v1511423861659" width="100%" height="300px" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

<?php
    }
?>