<div class="home-category-info">
    <div class="home-category-info-content">
        <div class="home-category-info-tese-wrapper">
            <a class="home-category-info-tese home-category-info-insight zoom-wrap" href="">
                <div class ="home-category-info-insight-img zoom-in" style="background-image: url(http://bonfect.localhost/media/wysiwyg/candys.jpg);"></div>
                <div class="home-category-info-insight-bg">
                    <div class="home-category-info-tese-content">
                        <h2>Confectionery</h2>
                    </div>
                </div>
            </a>
        </div>
        <div class="home-category-info-tab-words-wrapper">
            <div class="home-category-info-tab-words">
                <div class="home-category-info-tab-words-content">
                    <ul class="home-category-info-tab-words-line">
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>USA Confectionery</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/6/0/601179.jpg">
                            </a>
                        </li>
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>UK Confectionery</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/6/0/6012380_1.jpg">
                            </a>
                        </li>
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>Local Confectionery</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/6/0/6043414.jpg">
                            </a>
                        </li>
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>Hang Sell</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/6/0/600615.jpg">
                            </a>
                        </li>
                    </ul>
                    <ul class="home-category-info-tab-words-line">
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>Local Bulk Sugar</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/6/0/6070267.jpg">
                            </a>
                        </li>
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>Counter Line</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/i/m/image_123_1_289.jpg">
                            </a>
                        </li>
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>Gift Box</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/6/0/6076214.jpg">
                            </a>
                        </li>
                        <li class="home-category-info-tab-word zoom-wrap">
                            <a href="">
                                <div class="home-category-info-tab-word-content">
                                    <h3>Kids Novalties</h3>
                                </div>
                                <img class="home-category-info-norm-tab-word-img zoom-in" src="http://bonfect.localhost/media/catalog/product/cache/1/thumbnail/600x/17f82f742ffe127f42dca9de82fb58b1/6/0/6081089_1.jpg">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
